name: Build & Deploy Storybook Fix
on:
  push:
    branches:
      - 'fix/**'
  pull_request:
    branches:
      - 'fix/**'
jobs:
  build:
    name: Build Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Branch name
        run: echo running on branch ${GITHUB_REF#refs/heads/}

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install NPM packages
        run: |
          yarn

      - name: Update browserslist
        run: npx browserslist@latest --update-db

      - name: Build project and Storybook
        run: |
          yarn build
          yarn build-storybook -- -o sb-build-files
        env:
          CI: false

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: build-files
          path: ./sb-build-files


  deploy:
    name: Deploy Storybook
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build-files
          path: ./sb-build-files

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Deploy Storybook to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: storybook-gh-pages
          publish_dir: ./sb-build-files
          destination_dir: ${{ steps.extract_branch.outputs.branch }}